#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER


/* 自己写库——构建库函数雏形 */
#include "ra6m5_ioport.h"


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */


    /* 取消写保护 */
//    R_PMISC->PWPR = 0;                               ///< Clear BOWI bit - writing to PFSWE bit enabled
//    R_PMISC->PWPR = 1U << BSP_IO_PWPR_PFSWE_OFFSET;  ///< Set PFSWE bit - writing to PFS register enabled

    /* 调用取消写保护函数 */
    IOPORT_PinAccessEnable();


    /* 配置PFS寄存器 */
//    R_PFS->PORT[BSP_IO_PORT_00_PIN_06>>8].PIN[BSP_IO_PORT_00_PIN_06 & 0xFF].PmnPFS =
//        IOPORT_CFG_PORT_DIRECTION_OUTPUT | IOPORT_CFG_PORT_OUTPUT_HIGH;

    /* 使用 IOPORT 初始化结构体和调用初始化函数，替代手动配置PFS寄存器 */
    IOPORT_Init_t led_io_init;
    led_io_init.Port = IO_PORT_00;
    led_io_init.Pin = IO_PIN_06;
    led_io_init.Mode = IO_MODE_GPIO;    //普通GPIO模式，而不是复用功能模式或其他的
    led_io_init.Dir = IO_DIR_OUTPUT;
    led_io_init.OType = IO_OTYPE_PP;
    led_io_init.Drive = IO_DRIVE_LOW;
    led_io_init.Level = IO_LEVEL_HIGH;
    //LED_IO_Init.Pull = IO_NO_PULL; //端口方向处于输出模式下是用不了上拉的，所以这个属性没意义
    IOPORT_Init(&led_io_init); //调用初始化函数，进行初始化


    while(1)
    {
        /* 翻转LED灯 */
//        R_PORT0->PODR |= 1<<(BSP_IO_PORT_00_PIN_06 & 0xFF);
//        R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);
//        R_PORT0->PODR &= (uint16_t)~(1 << (BSP_IO_PORT_00_PIN_06 & 0xFF));
//        R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);

        /* 或者也可以这样 */
//        R_PORT0->PODR ^= 1<<(BSP_IO_PORT_00_PIN_06 & 0xFF);
//        R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);


        /* 使用函数 IOPORT_PinToggle 翻转引脚电平 */
        IOPORT_PinToggle(IO_PORT_00, IO_PIN_06);
        R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);
    }



#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
