#include <bsp_can_fd0.h>
#include "hal_data.h"
#include "retarget.h"
#include "bsp_uart.h"
#include "bsp_can_fd0.h"
#include "bsp_can_fd1.h"
#include "bsp_can_cfg.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER


#define LED_RED_IO_PIN    BSP_IO_PORT_06_PIN_01
#define LED_GREEN_IO_PIN  BSP_IO_PORT_06_PIN_04
#define LED_BLUE_IO_PIN   BSP_IO_PORT_06_PIN_02

#define LED_RED_ON()      R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED_IO_PIN, BSP_IO_LEVEL_LOW)
#define LED_GREEN_ON()    R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GREEN_IO_PIN, BSP_IO_LEVEL_LOW)
#define LED_BLUE_ON()     R_IOPORT_PinWrite(&g_ioport_ctrl, LED_BLUE_IO_PIN, BSP_IO_LEVEL_LOW)

#define LED_RED_OFF()     R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED_IO_PIN, BSP_IO_LEVEL_HIGH)
#define LED_GREEN_OFF()   R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GREEN_IO_PIN, BSP_IO_LEVEL_HIGH)
#define LED_BLUE_OFF()    R_IOPORT_PinWrite(&g_ioport_ctrl, LED_BLUE_IO_PIN, BSP_IO_LEVEL_HIGH)


//extern bool b_canfd_tx_complete;
//extern bool b_canfd_rx_complete;
//extern bool b_canfd_err_status;

/* Data to be loaded in Classic CAN and FD frames for transmission and acknowledgement */
volatile uint8_t tx_data[64] = "TX_MESG";
volatile uint8_t rx_data[64] = "RX_MESG";
volatile uint8_t tx_fd_data[64] = {0};
volatile uint8_t rx_fd_data[64] = {0};


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    __IO uint16_t temp = 0;

    bsp_uart4_init();

    bsp_canfd0_init();
    bsp_canfd1_init();

    printf("embedfire-野火 www.embedfire.com\r\n");

    //canfd0_operation();

    while(1)
    {
//        canfd1_operation();
//        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_SECONDS);
//        if (b_canfd0_rx_complete == true) {
//            b_canfd0_rx_complete = false;
//            printf("canfd0接收到数据\r\n");
//        }


        canfd0_operation();
        R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MILLISECONDS);
//        if (b_canfd1_rx_complete == true) {
//            b_canfd1_rx_complete = false;
//            printf("canfd1接收到数据\r\n");
//        }

        for( uint16_t j = 0; j < 64; j++)
        {
            tx_fd_data[j] = (uint8_t) (j + 1);
        }

        while(b_canfd1_rx_complete == false);
        b_canfd1_rx_complete = false;

        if(0 == strncmp((char*)&canfd1_rx_frame.data[0], (char*)&tx_fd_data[0], CAN_FD_DATA_LENGTH_CODE))
        {
            printf("canfd1接收到数据，且数据正常\r\n");
        }



        printf("\r\n\r\n\r\n");

        if (temp % 2 == 0) {
            LED_BLUE_ON();
        } else {
            LED_BLUE_OFF();
        }
        temp++;
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}






/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
