#include "hal_data.h"
#include "debug_uart.h"
#include "Flash.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

extern  volatile uint8_t uart_send_complete_flag;
void print(char *ptr)
{
	//printf("%c\r\n",*ptr);
	
	R_SCI_UART_Write(Debug_UART.p_ctrl, (uint8_t *)ptr, 1);
	while(uart_send_complete_flag == false) ;
	uart_send_complete_flag = false;
}
/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/


char g_dest[1024] = {};
uint8_t buffer[16] = {};

	
	
void Read_Manufacturer_and_Device_ID()	//96h
{
				unsigned char data[6] = {};
				data[0] = 0x9f;
				//R_QSPI_DirectWrite(Flash.p_ctrl, &data[0], 1 , false);	//false: close the spi  true: go go go
				R_QSPI->SFMCMD = 1U;
				R_QSPI->SFMPMD = 0x4;
				R_QSPI->SFMCOM = data[0];

				data[0] = (uint8_t) R_QSPI->SFMCOM;				
				data[1] = (uint8_t) R_QSPI->SFMCOM;			
				data[2] = (uint8_t) R_QSPI->SFMCOM;				

				R_QSPI->SFMCMD = 1U;
				R_QSPI->SFMCMD = 0U;
				R_QSPI->SFMPMD = 0x0;
				printf("%d\r\n",data[0]);
				printf("%d\r\n",data[1]);
				printf("%d\r\n",data[2]);
}

void Read_Manufacturer_and_Device_ID_1()
{
				unsigned char data[6] = {};
				data[0] = 0x9f;
				R_QSPI_DirectWrite(Flash.p_ctrl, &data[0], 1 , true);

				data[0] = (uint8_t) R_QSPI->SFMCOM;				
				data[1] = (uint8_t) R_QSPI->SFMCOM;			
				data[2] = (uint8_t) R_QSPI->SFMCOM;				

				R_QSPI->SFMCMD = 1U;
				R_QSPI->SFMCMD = 0U;
				printf("%d\r\n",data[0]);
				printf("%d\r\n",data[1]);
				printf("%d\r\n",data[2]);
}

void Read_ID()													//90h
{
				unsigned char data[6] = {};
				data[0] = 0x90;
				//R_QSPI_DirectWrite(Flash.p_ctrl, &data[0], 1 , false);	//false: close the spi  true: go go go
				R_QSPI->SFMCMD = 1U;
				R_QSPI->SFMPMD = 0x0;
				R_QSPI->SFMCOM = data[0];

				data[0] = (uint8_t) R_QSPI->SFMCOM;				
				data[1] = (uint8_t) R_QSPI->SFMCOM;			
				data[2] = (uint8_t) R_QSPI->SFMCOM;				

				data[0] = (uint8_t) R_QSPI->SFMCOM;				
				data[1] = (uint8_t) R_QSPI->SFMCOM;					
				R_QSPI->SFMCMD = 1U;
				R_QSPI->SFMCMD = 0U; //0x60000000
				R_QSPI->SFMPMD = 0x4;
				printf("%d\r\n",data[0]);
				printf("%d\r\n",data[1]);
				
}

void read_Unique_date()
{
		unsigned char data[6] = {};
		data[0] = 0x4B;
		data[1] = 0x01;
		data[2] = 0x01;
		data[3] = 0x01;
		data[3] = 0x01;
		R_QSPI_DirectWrite(Flash.p_ctrl, &data[0], 5 , true);

		data[0] = (uint8_t) R_QSPI->SFMCOM;				
		data[1] = (uint8_t) R_QSPI->SFMCOM;			
		data[2] = (uint8_t) R_QSPI->SFMCOM;	
		data[3] = (uint8_t) R_QSPI->SFMCOM;	
					
		R_QSPI->SFMCMD = 1U;
		R_QSPI->SFMCMD = 0U;
			
		printf("%d\r\n",data[0]);
		printf("%d\r\n",data[1]);
		printf("%d\r\n",data[2]);	
		printf("%d\r\n",data[3]);

}


void erase_pate()
{
		unsigned char data[6] = {};
		uint32_t adress;
		
		data[0] = 0x06;		//write_enable_command
		data[1]	= 0x20;		//erase_command
		adress = 0x000000;
		R_QSPI->SFMCMD = 1U;
		R_QSPI->SFMCOM = data[0];
		R_QSPI->SFMCMD = 1U;
    R_QSPI->SFMCOM = data[1];
		R_QSPI->SFMCOM = (uint8_t) (adress >> 16);
		R_QSPI->SFMCOM = (uint8_t) (adress >> 8);
		R_QSPI->SFMCOM = (uint8_t) (adress);
	  R_QSPI->SFMCMD = 1U;
    R_QSPI->SFMCMD = 0U;	
			
		R_BSP_SoftwareDelay(1,BSP_DELAY_UNITS_SECONDS);
}


void write_data()
{
		unsigned char data[6] = {};
		unsigned char send_data[32] = {0x01,0x02,0x03,0x04,0x05,0x06,};
		uint32_t adress;
		
		data[0] = 0x06;
		data[1]	= 0x02;
		adress = 0x000000;
		R_QSPI->SFMCMD = 1U;
		R_QSPI->SFMCOM = data[0];
		R_QSPI->SFMCMD = 1;
		R_QSPI->SFMCOM = data[1];
		R_QSPI->SFMCOM = (uint8_t) (adress >> 16);
		R_QSPI->SFMCOM = (uint8_t) (adress >> 8);
		R_QSPI->SFMCOM = (uint8_t) (adress);
		
		for(uint8_t i=0 ; i<6 ; i++)
		{
			R_QSPI->SFMCOM = send_data[i];
		}
		
	  R_QSPI->SFMCMD = 1U;
    R_QSPI->SFMCMD = 0U;		
		R_BSP_SoftwareDelay(1,BSP_DELAY_UNITS_SECONDS);		
}

void read_date()
{
		unsigned char data[6] = {};
		data[0] = 0x03;
		data[1] = 0x00;
		data[2] = 0x00;
		data[3] = 0x00;
		R_QSPI_DirectWrite(Flash.p_ctrl, &data[0], 4 , true);

		data[0] = (uint8_t) R_QSPI->SFMCOM;				
		data[1] = (uint8_t) R_QSPI->SFMCOM;			
		data[2] = (uint8_t) R_QSPI->SFMCOM;	
		data[3] = (uint8_t) R_QSPI->SFMCOM;					
		R_QSPI->SFMCMD = 1U;
		R_QSPI->SFMCMD = 0U;
			
		printf("%d\r\n",data[0]);
		printf("%d\r\n",data[1]);
		printf("%d\r\n",data[2]);	
		printf("%d\r\n",data[3]);
}



unsigned char data[6] = {};
void hal_entry(void)
{
		Debug_UART_Init();
		R_BSP_SoftwareDelay(1,BSP_DELAY_UNITS_SECONDS);
		R_QSPI_Open(Flash.p_ctrl, Flash.p_cfg);
		while(1)
		{
			erase_pate();
			write_data();
			read_date();
			//while(1);
			R_BSP_SoftwareDelay(1,BSP_DELAY_UNITS_SECONDS);
		}
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
